# Generated by Django 4.2.4 on 2023-08-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_room_code_remove_room_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='guest_can_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='votes_to_skip',
            field=models.IntegerField(default=1),
        ),
    ]
